In [2]:
import pandas as pd

posts = pd.read_csv("Social_Engine_Posts_Corrupted.csv")
users = pd.read_csv("Social_Engine_Users.csv")

print("Posts dataset:")
print(posts.shape)

print("\n Users dataset:")
print(users.shape)

print("\nPosts dtaset:")
print(posts.columns.tolist())

print("\nUsers columns:")
print(users.columns.tolist())

Posts dataset:
(12360, 8)

 Users dataset:
(1500, 5)

Posts dtaset:
['post_id', 'user_id', 'platform', 'text_content', 'timestamp', 'likes', 'shares', 'comments']

Users columns:
['user_id', 'location', 'language', 'account_created', 'follower_count']

In [4]:
print("MISSING VALUES IN POSTS:")
print(posts.isnull().sum())
print("\nMissing values in Users:")
print(users.isnull().sum())

MISSING VALUES IN POSTS:
post_id            0
user_id            0
platform        1846
text_content    1746
timestamp          0
likes           1858
shares             0
comments           0
dtype: int64

Missing values in Users:
user_id            0
location           0
language           0
account_created    0
follower_count     0
dtype: int64

In [5]:
print("Likes statistics:")
print(posts["likes"].describe())

print("\nNegative likes:")
print((posts["likes"] < 0).sum())

print("\nSmallest likes values:")
print(posts["likes"].sort_values().head(20))

print("\nLargest likes values:")
print(posts["likes"].sort_values(ascending=False).head(20))

Likes statistics:
count    10502.000000
mean      2247.075795
std       1797.342958
min      -4987.000000
25%       1038.250000
50%       2387.000000
75%       3664.000000
max       5000.000000
Name: likes, dtype: float64

Negative likes:
525

Smallest likes values:
7625    -4987.0
5616    -4975.0
971     -4964.0
4590    -4948.0
2241    -4941.0
12205   -4938.0
1264    -4914.0
8334    -4911.0
2877    -4904.0
2115    -4894.0
6525    -4881.0
9839    -4878.0
8111    -4868.0
4384    -4855.0
963     -4843.0
1747    -4830.0
6710    -4813.0
20      -4812.0
7526    -4802.0
9068    -4800.0
Name: likes, dtype: float64

Largest likes values:
2932     5000.0
734      5000.0
1871     5000.0
2262     5000.0
10397    4999.0
5511     4999.0
865      4999.0
12266    4998.0
11593    4998.0
7859     4998.0
6452     4997.0
2668     4997.0
752      4996.0
11833    4995.0
10570    4995.0
644      4994.0
11608    4992.0
2593     4992.0
501      4992.0
8997     4992.0
Name: likes, dtype: float64

In [6]:
negative_likes = posts[posts["likes"] < 0]

print("Number of negative-like records:", len(negative_likes))

print("\nNegative likes by platform:")
print(negative_likes["platform"].value_counts(dropna=False))

print("\nNegative likes by user:")
print(negative_likes["user_id"].value_counts().head(20))

print("\nNegative likes sample:")
display(negative_likes.head(10))

Number of negative-like records: 525

Negative likes by platform:
platform
Instagram    99
NaN          94
Twitter      94
YouTube      87
Reddit       80
Facebook     71
Name: count, dtype: int64

Negative likes by user:
user_id
user_nq5irbxf    5
user_ouwnxemr    3
user_5idgm0pl    3
user_potbol01    3
user_wawwrvtc    3
user_oknxkzax    3
user_bxh59css    3
user_hvqqyzoi    3
user_njyhr041    3
user_zsdvwipi    2
user_5hllls25    2
user_wous5rom    2
user_mjgvhs2g    2
user_bnum1ru1    2
user_ewvhln58    2
user_n4b1bcqh    2
user_jxoe2fqh    2
user_3l8kzask    2
user_katitpu9    2
user_cyqqg8x5    2
Name: count, dtype: int64

Negative likes sample:

,post_id,user_id,platform,text_content,timestamp,likes,shares,comments
20,mbykzpzh1l1y,user_750rlmnw,NaN,Could someone explain with my new Air Max from...,2024-07-16T02:21:20,-4812.0,1777,553
94,wal886ggp7kg,user_e3cwapff,YouTube,Loving it with my new Galaxy Tab from Samsung!...,1716427522,-1795.0,454,350
153,38tm1xfxxsdi,user_r7o639pp,Instagram,Should I upgrade about Samsung's Galaxy Buds? ...,2024-11-07T03:44:54,-3707.0,957,49
163,yktgh97ttawi,user_ral75hq0,Twitter,Has anyone else experienced battery problems w...,2024-10-27T19:52:17,-4543.0,363,703
188,loscndnlqi7b,user_xyvxp8vz,Twitter,Comparing Google Chromebook to the competition...,1744356362,-3194.0,904,378
192,hvjh643oxb8e,user_puypdmp1,YouTube,Just saw an ad for Apple iPad Air during the I...,2024-11-10T02:35:38,-3616.0,1728,363
197,0c0tc7wbhqdu,user_m2ziq5ox,Instagram,Comparing Google Nest Thermostat to the compet...,2025-03-14T22:02:13,-1165.0,709,403
263,dnhsqcx3t94w,user_oknxkzax,Twitter,Cannot believe with my new Galaxy Buds from Sa...,2025-02-04T18:06:24,-738.0,980,503
266,5fbt4nzjxol9,user_t2e8zk5w,Reddit,NaN,1725489386,-851.0,1959,185
268,whsvb3faauwf,user_uod57rwt,Facebook,Has anyone else experienced connectivity issue...,2025-02-07T14:38:01,-1205.0,1413,976

In [7]:
negative_likes = posts[posts["likes"] < 0].copy()

negative_likes["abs_likes"] = negative_likes["likes"].abs()

print("Negative likes summary:")
print(negative_likes["likes"].describe())

print("\nAbsolute value summary:")
print(negative_likes["abs_likes"].describe())

print("\nCorrelation with shares:")
print(negative_likes[["abs_likes", "shares"]].corr())

print("\nCorrelation with comments:")
print(negative_likes[["abs_likes", "comments"]].corr())

Negative likes summary:
count     525.000000
mean    -2457.240000
std      1426.570583
min     -4987.000000
25%     -3640.000000
50%     -2388.000000
75%     -1205.000000
max       -11.000000
Name: likes, dtype: float64

Absolute value summary:
count     525.000000
mean     2457.240000
std      1426.570583
min        11.000000
25%      1205.000000
50%      2388.000000
75%      3640.000000
max      4987.000000
Name: abs_likes, dtype: float64

Correlation with shares:
           abs_likes    shares
abs_likes   1.000000  0.022999
shares      0.022999  1.000000

Correlation with comments:
           abs_likes  comments
abs_likes     1.0000   -0.0605
comments     -0.0605    1.0000

In [8]:
print("SHARES STATISTICS:")
print(posts["shares"].describe())

print("\nNegative shares:")
print((posts["shares"] < 0).sum())

print("\nCOMMENTS STATISTICS:")
print(posts["comments"].describe())

print("\nNegative comments:")
print((posts["comments"] < 0).sum())

SHARES STATISTICS:
count    12360.000000
mean      1005.867557
std        574.734542
min          0.000000
25%        509.000000
50%       1016.000000
75%       1499.000000
max       2000.000000
Name: shares, dtype: float64

Negative shares:
0

COMMENTS STATISTICS:
count    12360.000000
mean       504.081958
std        288.796752
min          0.000000
25%        252.000000
50%        503.000000
75%        755.000000
max       1000.000000
Name: comments, dtype: float64

Negative comments:
0

In [9]:
print("Sample timestamps:")
print(posts["timestamp"].head(20).to_string(index=False))

print("\nNumber of unique timestamp formats:")
print(posts["timestamp"].astype(str).str.len().value_counts())

print("\nExamples of different timestamp lengths:")

for length in posts["timestamp"].astype(str).str.len().unique():
    print("\nLength:", length)
    print(posts.loc[posts["timestamp"].astype(str).str.len() == length, "timestamp"].head(5).tolist())

Sample timestamps:
         25-09-2024
         1722528840
2025-04-13T20:12:18
         10-09-2024
         31-05-2024
         24-01-2025
         1719394663
2025-03-27T13:44:32
2024-05-05T05:52:34
         11-02-2025
2024-06-11T14:54:47
         1736393335
         1725467245
         15-02-2025
         1731343668
         1740278648
         14-12-2024
         1716471784
         1733293947
         1732652943

Number of unique timestamp formats:
timestamp
10    7410
19    4950
Name: count, dtype: int64

Examples of different timestamp lengths:

Length: 10
['25-09-2024', '1722528840', '10-09-2024', '31-05-2024', '24-01-2025']

Length: 19
['2025-04-13T20:12:18', '2025-03-27T13:44:32', '2024-05-05T05:52:34', '2024-06-11T14:54:47', '2024-07-16T02:21:20']

In [10]:
unix_timestamps = posts[
    posts["timestamp"].astype(str).str.fullmatch(r"\d{10}")
]["timestamp"]

converted_unix = pd.to_datetime(
    unix_timestamps.astype(int),
    unit="s",
    errors="coerce"
)

print("Number of 10-digit numeric timestamps:", len(unix_timestamps))
print("Invalid Unix timestamps:", converted_unix.isna().sum())

print("\nConverted Unix timestamp examples:")
print(converted_unix.head(10))

Number of 10-digit numeric timestamps: 3788
Invalid Unix timestamps: 0

Converted Unix timestamp examples:
1    2024-08-01 16:14:00
6    2024-06-26 09:37:43
11   2025-01-09 03:28:55
12   2024-09-04 16:27:25
14   2024-11-11 16:47:48
15   2025-02-23 02:44:08
17   2024-05-23 13:43:04
18   2024-12-04 06:32:27
19   2024-11-26 20:29:03
21   2025-03-19 04:05:04
Name: timestamp, dtype: datetime64[ns]

In [11]:
date_format = posts[
    posts["timestamp"].astype(str).str.fullmatch(r"\d{2}-\d{2}-\d{4}")
]["timestamp"]

converted_dates = pd.to_datetime(
    date_format,
    format="%d-%m-%Y",
    errors="coerce"
)

print("Number of DD-MM-YYYY dates:", len(date_format))
print("Invalid DD-MM-YYYY dates:", converted_dates.isna().sum())

print("\nConverted date examples:")
print(converted_dates.head(10))

Number of DD-MM-YYYY dates: 3622
Invalid DD-MM-YYYY dates: 0

Converted date examples:
0    2024-09-25
3    2024-09-10
4    2024-05-31
5    2025-01-24
9    2025-02-11
13   2025-02-15
16   2024-12-14
23   2025-04-12
24   2024-09-06
26   2025-03-14
Name: timestamp, dtype: datetime64[ns]

In [12]:
print("Platform frequency:")
print(posts["platform"].value_counts(dropna=False))

Platform frequency:
platform
YouTube      2136
Facebook     2135
Twitter      2119
Reddit       2086
Instagram    2038
NaN          1846
Name: count, dtype: int64

In [13]:
posts["platform"].fillna("YouTube")

0           Reddit
1           Reddit
2          YouTube
3         Facebook
4           Reddit
           ...
12355     Facebook
12356     Facebook
12357      YouTube
12358    Instagram
12359      YouTube
Name: platform, Length: 12360, dtype: object

In [14]:
missing_platform = posts[posts["platform"].isna()]

print("Number of posts with missing platform:", len(missing_platform))

display(
    missing_platform[["post_id", "user_id", "platform", "text_content"]].head(20)
)

Number of posts with missing platform: 1846

,post_id,user_id,platform,text_content
2,dvvhg8eel45x,user_nfo3ih5u,NaN,Just unboxed my new Highlander from Toyota. Ex...
5,f85c8vm8ac8l,user_aedwfomw,NaN,Adidas ValentinesDeals is disappointing! Can't...
10,cvdgyqy7xoq6,user_wv5x4t03,NaN,Just saw an ad for Samsung Galaxy Buds during ...
16,cpiun4hvwfns,user_tb4fgpus,NaN,My two days review of Nike Dri-FIT: Not worth ...
20,mbykzpzh1l1y,user_750rlmnw,NaN,Could someone explain with my new Air Max from...
35,i6io9jo0vpxa,user_y5urixy6,NaN,Comparing Pepsi Pepsi Lime to the competition....
39,d25e0a89eti4,user_va78mz39,NaN,Coca-Cola BlackFriday is okay! Can't wait to s...
42,sqdh2jbaeloe,user_ju8hqhh7,NaN,Comparing Adidas Samba to the competition. Exc...
44,juovcq3m427s,user_h39vyus8,NaN,NaN
53,ym0fk6gqthz3,user_ivpoy0x1,NaN,Comparing Pepsi Pepsi Lime to the competition....
60,df1al5tr1oca,user_yti77nnr,NaN,Comparing Pepsi Pepsi Zero Sugar to the compet...
63,2r1k9opcv2z7,user_g8q08z4s,NaN,Comparing Apple iMac to the competition. Highl...
80,5gyyfd2wv95z,user_3o7w66o2,NaN,My three months review of Coca-Cola Diet Coke:...
83,w0lnzrqoiyej,user_hen7rrkk,NaN,NaN
89,59gdx6c1r4pz,user_eh4ki1e0,NaN,NaN
91,gqndmf8vvpb2,user_z9ike75w,NaN,NULL&amp;
92,zg7a98dozipg,user_mtg94j65,NaN,Just unboxed my new Epic React from Nike. Exce...
95,l8jdu7zmt65h,user_zq2nib62,NaN,Just tried the Gazelle from Adidas. Not worth ...
96,3u65pggx1zxm,user_zwe31kzt,NaN,Comparing Samsung Galaxy Tab to the competitio...
104,mvcesgjn0bv0,user_4h2i9jla,NaN,NaN

In [17]:
print("Missing text values:")
print(posts["text_content"].isna().sum())

print("\nText values containing NULL:")
print(
    posts["text_content"]
    .astype(str)
    .str.contains("NULL", case=False, na=False)
    .sum()
)

print("\nText values containing HTML:")
print(
    posts["text_content"]
    .astype(str)
    .str.contains("<|>|&amp;|&lt;|&gt;", regex=True, na=False)
    .sum()
)

print("\nExamples of suspicious text:")
display(
    posts[
        posts["text_content"].astype(str)
        .str.contains("NULL|<|>|&amp;|&lt;|&gt;",
                      case=False, regex=True, na=False)
    ][["post_id", "text_content"]].head(20)
)

Missing text values:
1746

Text values containing NULL:
94

Text values containing HTML:
1004

Examples of suspicious text:

          post_id                                       text_content
0    to64mgey2v3y  Bummed out with my new Air Max from Nike! Abso...
19   ckz4ciuuw7c5  Has anyone else experienced delivery delays wi...
48   xd96337v76wx  Just tried the Superstar from Adidas. Wouldn't...
52   s5rqx7wko7m1  Confused about with my new Sienna from Toyota!...
63   2r1k9opcv2z7  Comparing Apple iMac to the competition. Highl...
65   p7h083r7vums  Just saw an ad for Samsung Neo QLED TV during ...
71   wd436n6ouxir  How do I fix about Google's Pixel Watch? @Cele...
91   gqndmf8vvpb2                                          NULL&amp;
92   zg7a98dozipg  Just unboxed my new Epic React from Nike. Exce...
97   9aebqwidw4n6  Has anyone else experienced software bugs with...
102  96xkquvldqrm  Comparing Google Pixel Watch to the competitio...
111  szo0hhgxcbvn  My one week review of Coca-Cola Fanta: As expe...
116  zf1w3c9xs1gd  Adidas HolidaySpecial is standard! Can't wait ...
128  wrpuf437gh64  Thrilled with my new Yeezy from Adidas! Had is...
133  nap5vkbmyrys                                          NULL&amp;
154  ca41scke5hc1  Just tried the Pixel Watch from Google. Highly...
176  ggm0o09gniaq  Apple ValentinesDeals is okay! Can't wait to s...
191  gnfocz2o4mv6                                          NULL&amp;
195  u085n5n0c3xw  Apple InnovationX is impressive! Can't wait to...
198  kjujs5t6d3fq  Any advice about Amazon's Eero WiFi? @ReviewSi...

In [18]:
html_rows = posts[
    posts["text_content"].astype(str).str.contains(
        r"<|>|&amp;|&lt;|&gt;|&quot;|&#",
        regex=True,
        na=False
    )
]

print("Number of rows with HTML/encoded content:", len(html_rows))

for text in html_rows["text_content"].head(20):
    print("\nRAW:")
    print(repr(text))

Number of rows with HTML/encoded content: 1004

RAW:
'Bummed out with my new Air Max from Nike! Absolutely loving it. #Travel, #CustomerService, #Fashion&amp;'

RAW:
"Has anyone else experienced delivery delays with Nike's Epic React? Had issues with it. @ReviewSite, @BrandSupport #ProductLaunch, #Affordable&amp;"

RAW:
"Just tried the Superstar from Adidas. Wouldn't recommend. #MustHave, #Deal Would love to get your feedback!<div>"

RAW:
'Confused about with my new Sienna from Toyota! Had issues with it. #MustHave, #Affordable, #Fitness&amp;'

RAW:
'Comparing Apple iMac to the competition. Highly recommend. #SpecialOffer Would love to get your feedback!&amp;'

RAW:
'Just saw an ad for Samsung Neo QLED TV during the ValentinesDeals. Absolutely loving it. #Affordable, #BestValue, #TrendAlert<br>'

RAW:
"How do I fix about Google's Pixel Watch? @CelebrityName, @MarketingTeam #SpecialOffer, #Exclusive Would love to get your feedback!&amp;"

RAW:
'NULL&amp;'

RAW:
'Just unboxed my new Epic React from Nike. Exceeded my expectations. Fed up #Trending, #Tech, #Limited<br>'

RAW:
"Has anyone else experienced software bugs with Toyota's RAV4? Returning it ASAP. @NewsOutlet #Discount, #Travel, #NewRelease&amp;"

RAW:
'Comparing Google Pixel Watch to the competition. Absolutely loving it. #Exclusive, #Fitness Really interested in hearing your thoughts!<br>'

RAW:
'My one week review of Coca-Cola Fanta: As expected. #Promo, #Food Really interested in hearing your thoughts!&amp;'

RAW:
"Adidas HolidaySpecial is standard! Can't wait to see what's coming next. #Promo, #Discount Let me know what you think!&amp;"

RAW:
'Thrilled with my new Yeezy from Adidas! Had issues with it. #Food, #Premium, #Quality Let me know what you think!&amp;'

RAW:
'NULL&amp;'

RAW:
'Just tried the Pixel Watch from Google. Highly recommend. #CustomerService Would love to get your feedback!<br>'

RAW:
"Apple ValentinesDeals is okay! Can't wait to see what's coming next. #NewRelease Let me know what you think!&amp;"

RAW:
'NULL&amp;'

RAW:
"Apple InnovationX is impressive! Can't wait to see what's coming next. #TrendAlert Would love to get your feedback!<div>"

RAW:
"Any advice about Amazon's Eero WiFi? @ReviewSite #Deal, #ProductLaunch, #MustHave Let me know what you think!&amp;"

In [19]:
print("Exact duplicate rows:")
print(posts.duplicated().sum())

print("\nDuplicate post IDs:")
print(posts["post_id"].duplicated().sum())

print("\nNumber of unique post IDs:")
print(posts["post_id"].nunique())

Exact duplicate rows:
360

Duplicate post IDs:
360

Number of unique post IDs:
12000

In [20]:
post_user_ids = set(posts["user_id"])
user_ids = set(users["user_id"])

missing_users = post_user_ids - user_ids

print("Unique users in Posts:", len(post_user_ids))
print("Unique users in Users:", len(user_ids))
print("Users referenced in Posts but missing from Users:", len(missing_users))

if len(missing_users) > 0:
    print("\nMissing user IDs:")
    print(list(missing_users)[:20])

Unique users in Posts: 1500
Unique users in Users: 1500
Users referenced in Posts but missing from Users: 0

In [21]:
print("Exact duplicate rows in Users:")
print(users.duplicated().sum())

print("\nDuplicate user IDs:")
print(users["user_id"].duplicated().sum())

print("\nUnique user IDs:")
print(users["user_id"].nunique())

Exact duplicate rows in Users:
0

Duplicate user IDs:
0

Unique user IDs:
1500

In [22]:
# Create copies so the original datasets remain unchanged
posts_clean = posts.copy()
users_clean = users.copy()

# Remove exact duplicate rows from Posts
before = len(posts_clean)

posts_clean = posts_clean.drop_duplicates()

after = len(posts_clean)

print("Posts before removing duplicates:", before)
print("Posts after removing duplicates:", after)
print("Duplicate rows removed:", before - after)

Posts before removing duplicates: 12360
Posts after removing duplicates: 12000
Duplicate rows removed: 360

In [23]:
# Check missing platforms before cleaning
print("Missing platforms before cleaning:")
print(posts_clean["platform"].isna().sum())

# Replace missing platform values with "Unknown"
posts_clean["platform"] = posts_clean["platform"].fillna("Unknown")

# Check the result
print("\nMissing platforms after cleaning:")
print(posts_clean["platform"].isna().sum())

print("\nPlatform distribution after cleaning:")
print(posts_clean["platform"].value_counts())

Missing platforms before cleaning:
0

Missing platforms after cleaning:
0

Platform distribution after cleaning:
platform
Facebook     2074
YouTube      2073
Twitter      2049
Reddit       2031
Instagram    1989
Unknown      1784
Name: count, dtype: int64

In [24]:
# Check NULL markers after duplicate removal

null_text = posts_clean[
    posts_clean["text_content"].astype(str).str.strip().str.contains(
        r"^NULL",
        case=False,
        regex=True,
        na=False
    )
]

print("NULL-type text values:", len(null_text))

print("\nExamples:")
display(null_text[["post_id", "text_content"]].head(10))

NULL-type text values: 91

Examples:

          post_id text_content
91   gqndmf8vvpb2    NULL&amp;
133  nap5vkbmyrys    NULL&amp;
191  gnfocz2o4mv6    NULL&amp;
202  2kyipmb8gn3r       NULLÃ©
245  xe673nhgfbbr    NULL&amp;
317  drehaxyr40ng    NULL<div>
375  5rk6uf9nmtef    NULL&amp;
453  6pjw2yoog1vi     NULL\n\n
477  vov15c8f9hn4     NULL<br>
659  okccaur7ruf2       NULLÃ©

In [25]:
# Convert corrupted NULL-type text values into actual missing values

null_mask = posts_clean["text_content"].astype(str).str.strip().str.contains(
    r"^NULL",
    case=False,
    regex=True,
    na=False
)

posts_clean.loc[null_mask, "text_content"] = pd.NA

print("NULL-type values converted to missing:", null_mask.sum())

print("\nMissing text values after this step:")
print(posts_clean["text_content"].isna().sum())

NULL-type values converted to missing: 91

Missing text values after this step:
1779

In [26]:
import re
import html

def clean_text(text):
    if pd.isna(text):
        return text

    text = str(text)

    # Remove HTML tags such as <div>, <br>, etc.
    text = re.sub(r"<[^>]+>", "", text)

    # Decode HTML entities such as &amp;, &quot;, etc.
    text = html.unescape(text)

    # Remove extra whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

# Apply the cleaning function
posts_clean["text_content"] = posts_clean["text_content"].apply(clean_text)

print("Text cleaning applied successfully.")

print("\nExamples after cleaning:")
display(posts_clean[["post_id", "text_content"]].head(10))

Text cleaning applied successfully.

Examples after cleaning:

        post_id                                       text_content
0  to64mgey2v3y  Bummed out with my new Air Max from Nike! Abso...
1  7f0wdauzbj89  My one month review of Pepsi Crystal Pepsi: Hi...
2  dvvhg8eel45x  Just unboxed my new Highlander from Toyota. Ex...
3  hgb9cxke4t7b  Comparing Pepsi Crystal Pepsi to the competiti...
4  zwerpw3wk320  My one week review of Coca-Cola Diet Coke: Bes...
5  f85c8vm8ac8l  Adidas ValentinesDeals is disappointing! Can't...
6  19ys654yi1if  Fed up with my new iPhone 15 from Apple! Best ...
7  5jywsz1bu0kp  Just unboxed my new React from Nike. Not bad. ...
8  ol0ai4w126p0  Just saw an ad for Toyota Highlander during th...
9  irjlew2pr8sw  Just unboxed my new iMac from Apple. Disappoin...

In [27]:
# Check for remaining HTML tags or HTML entities

remaining_html = posts_clean[
    posts_clean["text_content"].astype(str).str.contains(
        r"<[^>]+>|&(?:amp|lt|gt|quot|apos);|&#\d+;",
        regex=True,
        na=False
    )
]

print("Rows with remaining HTML/encoded artifacts:", len(remaining_html))

if len(remaining_html) > 0:
    print("\nExamples:")
    display(remaining_html[["post_id", "text_content"]].head(20))

Rows with remaining HTML/encoded artifacts: 91

Examples:

           post_id text_content
91    gqndmf8vvpb2         <NA>
133   nap5vkbmyrys         <NA>
191   gnfocz2o4mv6         <NA>
202   2kyipmb8gn3r         <NA>
245   xe673nhgfbbr         <NA>
317   drehaxyr40ng         <NA>
375   5rk6uf9nmtef         <NA>
453   6pjw2yoog1vi         <NA>
477   vov15c8f9hn4         <NA>
659   okccaur7ruf2         <NA>
767   hjr444zy7jra         <NA>
857   uj6p0712dxnc         <NA>
1033  uwxsmp4ljm6c         <NA>
1102  7c9nozhw51xg         <NA>
1107  uv23764m2pd3         <NA>
1130  c0955hcbuvc7         <NA>
1192  q2qg5j6im43j         <NA>
1561  65gsj2nqid6j         <NA>
1776  9bey0vindl28         <NA>
1779  stc034ffn6z2         <NA>

In [28]:
# Check remaining HTML/encoded artifacts, ignoring missing values

remaining_html = posts_clean[
    posts_clean["text_content"].notna()
    & posts_clean["text_content"].str.contains(
        r"<[^>]+>|&(?:amp|lt|gt|quot|apos);|&#\d+;",
        regex=True,
        na=False
    )
]

print("Rows with remaining HTML/encoded artifacts:", len(remaining_html))

if len(remaining_html) > 0:
    print("\nExamples:")
    display(remaining_html[["post_id", "text_content"]].head(20))

Rows with remaining HTML/encoded artifacts: 0

In [29]:
# Identify valid likes
valid_likes = posts_clean[
    posts_clean["likes"].notna() &
    (posts_clean["likes"] >= 0)
]["likes"]

print("Number of valid likes:", len(valid_likes))

print("\nValid likes statistics:")
print(valid_likes.describe())

print("\nMedian of valid likes:", valid_likes.median())

print("\nNumber of missing likes:", posts_clean["likes"].isna().sum())

print("Number of negative likes:", (posts_clean["likes"] < 0).sum())

Number of valid likes: 9677

Valid likes statistics:
count    9677.000000
mean     2493.505115
std      1438.286521
min         0.000000
25%      1240.000000
50%      2502.000000
75%      3724.000000
max      5000.000000
Name: likes, dtype: float64

Median of valid likes: 2502.0

Number of missing likes: 1814
Number of negative likes: 509

In [30]:
# Convert negative likes to missing values
negative_mask = posts_clean["likes"] < 0

print("Negative likes before cleaning:", negative_mask.sum())

posts_clean.loc[negative_mask, "likes"] = pd.NA

print("Negative likes after cleaning:")
print((posts_clean["likes"] < 0).sum())

print("\nTotal missing likes now:")
print(posts_clean["likes"].isna().sum())

Negative likes before cleaning: 509
Negative likes after cleaning:
0

Total missing likes now:
2323

In [31]:
# Calculate the median from valid likes
likes_median = posts_clean["likes"].median()

print("Median used for imputation:", likes_median)

# Fill missing likes with the median
posts_clean["likes"] = posts_clean["likes"].fillna(likes_median)

# Verify
print("\nMissing likes after imputation:")
print(posts_clean["likes"].isna().sum())

print("\nNegative likes after imputation:")
print((posts_clean["likes"] < 0).sum())

Median used for imputation: 2502.0

Missing likes after imputation:
0

Negative likes after imputation:
0

In [32]:
def convert_timestamp(value):
    if pd.isna(value):
        return pd.NaT

    value = str(value).strip()

    # 10-digit Unix timestamp
    if re.fullmatch(r"\d{10}", value):
        return pd.to_datetime(int(value), unit="s", errors="coerce")

    # DD-MM-YYYY format
    if re.fullmatch(r"\d{2}-\d{2}-\d{4}", value):
        return pd.to_datetime(
            value,
            format="%d-%m-%Y",
            errors="coerce"
        )

    # ISO format or other standard datetime representation
    return pd.to_datetime(value, errors="coerce")


# Convert timestamps
posts_clean["timestamp"] = posts_clean["timestamp"].apply(convert_timestamp)

print("Missing/invalid timestamps after conversion:")
print(posts_clean["timestamp"].isna().sum())

print("\nTimestamp examples after conversion:")
print(posts_clean["timestamp"].head(10))

Missing/invalid timestamps after conversion:
0

Timestamp examples after conversion:
0   2024-09-25 00:00:00
1   2024-08-01 16:14:00
2   2025-04-13 20:12:18
3   2024-09-10 00:00:00
4   2024-05-31 00:00:00
5   2025-01-24 00:00:00
6   2024-06-26 09:37:43
7   2025-03-27 13:44:32
8   2024-05-05 05:52:34
9   2025-02-11 00:00:00
Name: timestamp, dtype: datetime64[ns]

In [33]:
# Check missing text before filling
print("Missing text before filling:")
print(posts_clean["text_content"].isna().sum())

# Fill missing text with an explicit placeholder
posts_clean["text_content"] = posts_clean["text_content"].fillna("Unknown")

# Verify
print("\nMissing text after filling:")
print(posts_clean["text_content"].isna().sum())

print("\nNumber of 'Unknown' text values:")
print((posts_clean["text_content"] == "Unknown").sum())

Missing text before filling:
1779

Missing text after filling:
0

Number of 'Unknown' text values:
1779

In [34]:
print("LOCATION VALUES:")
print(users_clean["location"].value_counts(dropna=False).head(20))

print("\nLANGUAGE VALUES:")
print(users_clean["language"].value_counts(dropna=False))

print("\nFOLLOWER COUNT STATISTICS:")
print(users_clean["follower_count"].describe())

print("\nNegative follower counts:")
print((users_clean["follower_count"] < 0).sum())

LOCATION VALUES:
location
Shanghai, China               56
Barcelona, Spain              56
Los Angeles, USA              55
Munich, Germany               54
Dubai, UAE                    53
Mumbai, India                 53
Milan, Italy                  53
Melbourne, Australia          52
Beijing, China                51
Chicago, USA                  50
Osaka, Japan                  50
Houston, USA                  50
Rio de Janeiro, Brazil        49
Singapore                     49
New York, USA                 48
Johannesburg, South Africa    48
Toronto, Canada               45
London, UK                    45
Paris, France                 45
São Paulo, Brazil             44
Name: count, dtype: int64

LANGUAGE VALUES:
language
zh    168
ja    156
hi    156
en    153
fr    150
es    146
ru    144
ar    143
pt    143
de    141
Name: count, dtype: int64

FOLLOWER COUNT STATISTICS:
count     1500.000000
mean     24964.019333
std      14185.477457
min        109.000000
25%      12771.750000
50%      24741.500000
75%      37097.250000
max      49944.000000
Name: follower_count, dtype: float64

Negative follower counts:
0

In [35]:
print("LIKES:")
print(posts_clean["likes"].describe())
print("Missing:", posts_clean["likes"].isna().sum())
print("Negative:", (posts_clean["likes"] < 0).sum())

print("\nSHARES:")
print(posts_clean["shares"].describe())
print("Missing:", posts_clean["shares"].isna().sum())
print("Negative:", (posts_clean["shares"] < 0).sum())

print("\nCOMMENTS:")
print(posts_clean["comments"].describe())
print("Missing:", posts_clean["comments"].isna().sum())
print("Negative:", (posts_clean["comments"] < 0).sum())

LIKES:
count    12000.000000
mean      2495.149583
std       1291.582881
min          0.000000
25%       1547.000000
50%       2502.000000
75%       3450.000000
max       5000.000000
Name: likes, dtype: float64
Missing: 0
Negative: 0

SHARES:
count    12000.000000
mean      1007.167167
std        575.072282
min          0.000000
25%        510.000000
50%       1018.000000
75%       1501.000000
max       2000.000000
Name: shares, dtype: float64
Missing: 0
Negative: 0

COMMENTS:
count    12000.00000
mean       504.34575
std        288.68416
min          0.00000
25%        253.00000
50%        503.00000
75%        755.00000
max       1000.00000
Name: comments, dtype: float64
Missing: 0
Negative: 0

In [36]:
print("========== FINAL CLEANING VALIDATION ==========")

print("\nDataset shape:")
print(posts_clean.shape)

print("\nMissing values:")
print(posts_clean.isna().sum())

print("\nDuplicate rows:")
print(posts_clean.duplicated().sum())

print("\nDuplicate post IDs:")
print(posts_clean["post_id"].duplicated().sum())

print("\nNegative likes:")
print((posts_clean["likes"] < 0).sum())

print("\nNegative shares:")
print((posts_clean["shares"] < 0).sum())

print("\nNegative comments:")
print((posts_clean["comments"] < 0).sum())

print("\nInvalid timestamps:")
print(posts_clean["timestamp"].isna().sum())

print("\nUnique users in Posts:")
print(posts_clean["user_id"].nunique())

print("\nUsers in Users dataset:")
print(users_clean["user_id"].nunique())

print("\n==============================================")

========== FINAL CLEANING VALIDATION ==========

Dataset shape:
(12000, 8)

Missing values:
post_id         0
user_id         0
platform        0
text_content    0
timestamp       0
likes           0
shares          0
comments        0
dtype: int64

Duplicate rows:
0

Duplicate post IDs:
0

Negative likes:
0

Negative shares:
0

Negative comments:
0

Invalid timestamps:
0

Unique users in Posts:
1500

Users in Users dataset:
1500

==============================================

In [37]:
# Platform distribution

platform_counts = posts_clean["platform"].value_counts()

print("Posts by platform:")
print(platform_counts)

print("\nPercentage of posts by platform:")
print((platform_counts / len(posts_clean) * 100).round(2))

Posts by platform:
platform
Facebook     2074
YouTube      2073
Twitter      2049
Reddit       2031
Instagram    1989
Unknown      1784
Name: count, dtype: int64

Percentage of posts by platform:
platform
Facebook     17.28
YouTube      17.27
Twitter      17.08
Reddit       16.92
Instagram    16.58
Unknown      14.87
Name: count, dtype: float64

In [38]:
# Average engagement by platform

platform_engagement = posts_clean.groupby("platform")[
    ["likes", "shares", "comments"]
].mean().round(2)

print("Average engagement by platform:")
print(platform_engagement)

Average engagement by platform:
             likes   shares  comments
platform
Facebook   2521.94   984.17    506.94
Instagram  2495.99  1040.84    499.80
Reddit     2490.37  1002.23    511.18
Twitter    2452.51  1005.39    506.13
Unknown    2484.95   998.61    496.54
YouTube    2523.14  1011.83    504.38

In [39]:
# Correlation between engagement metrics

engagement_corr = posts_clean[
    ["likes", "shares", "comments"]
].corr()

print("Engagement correlation matrix:")
print(engagement_corr.round(3))

Engagement correlation matrix:
          likes  shares  comments
likes     1.000  -0.003     0.012
shares   -0.003   1.000     0.024
comments  0.012   0.024     1.000

In [40]:
# Detailed engagement distribution

print("LIKES distribution:")
print(posts_clean["likes"].describe(percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]))

print("\nSHARES distribution:")
print(posts_clean["shares"].describe(percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]))

print("\nCOMMENTS distribution:")
print(posts_clean["comments"].describe(percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]))

LIKES distribution:
count    12000.000000
mean      2495.149583
std       1291.582881
min          0.000000
1%          65.990000
5%         321.950000
25%       1547.000000
50%       2502.000000
75%       3450.000000
95%       4685.000000
99%       4937.020000
max       5000.000000
Name: likes, dtype: float64

SHARES distribution:
count    12000.000000
mean      1007.167167
std        575.072282
min          0.000000
1%          21.990000
5%         100.950000
25%        510.000000
50%       1018.000000
75%       1501.000000
95%       1901.000000
99%       1977.010000
max       2000.000000
Name: shares, dtype: float64

COMMENTS distribution:
count    12000.00000
mean       504.34575
std        288.68416
min          0.00000
1%          11.00000
5%          51.00000
25%        253.00000
50%        503.00000
75%        755.00000
95%        948.00000
99%        989.00000
max       1000.00000
Name: comments, dtype: float64

In [41]:
# Create a monthly time series

posts_clean["month"] = posts_clean["timestamp"].dt.to_period("M")

monthly_posts = posts_clean.groupby("month").size()

print("Date range:")
print("Start:", posts_clean["timestamp"].min())
print("End:", posts_clean["timestamp"].max())

print("\nPosts per month:")
print(monthly_posts)

Date range:
Start: 2024-05-01 00:00:00
End: 2025-04-30 21:57:10

Posts per month:
month
2024-05    1038
2024-06     979
2024-07     996
2024-08    1015
2024-09     974
2024-10    1029
2024-11    1025
2024-12    1035
2025-01    1007
2025-02     914
2025-03    1013
2025-04     975
Freq: M, dtype: int64

In [42]:
# Average engagement by month

monthly_engagement = posts_clean.groupby("month")[
    ["likes", "shares", "comments"]
].mean().round(2)

print("Average monthly engagement:")
print(monthly_engagement)

Average monthly engagement:
           likes   shares  comments
month
2024-05  2463.67   992.53    510.56
2024-06  2429.34   998.87    504.01
2024-07  2463.60  1025.69    485.13
2024-08  2568.97  1019.43    494.40
2024-09  2530.08  1002.43    492.42
2024-10  2539.16  1004.93    511.66
2024-11  2509.93  1000.55    514.73
2024-12  2510.14  1039.64    504.36
2025-01  2429.86   997.88    499.66
2025-02  2461.46   999.89    510.42
2025-03  2547.34  1002.80    509.87
2025-04  2482.12   999.93    514.71

In [43]:
# Top 10 posts by each engagement metric

print("TOP 10 POSTS BY LIKES")
display(
    posts_clean[
        ["post_id", "platform", "likes", "shares", "comments", "text_content"]
    ]
    .sort_values("likes", ascending=False)
    .head(10)
)

print("\nTOP 10 POSTS BY SHARES")
display(
    posts_clean[
        ["post_id", "platform", "likes", "shares", "comments", "text_content"]
    ]
    .sort_values("shares", ascending=False)
    .head(10)
)

print("\nTOP 10 POSTS BY COMMENTS")
display(
    posts_clean[
        ["post_id", "platform", "likes", "shares", "comments", "text_content"]
    ]
    .sort_values("comments", ascending=False)
    .head(10)
)

TOP 10 POSTS BY LIKES

,post_id,platform,likes,shares,comments,text_content
2262,fvvna7s3i8o9,YouTube,5000.0,1056,246,So happy with my new Air Max from Nike! Does t...
1871,d3rmd137wehn,Facebook,5000.0,1735,184,Has anyone else experienced software bugs with...
734,a3vh0wesnhg2,Instagram,5000.0,693,20,Has anyone else experienced customer service w...
2932,87gq6xrd3ykv,Reddit,5000.0,824,401,My one year review of Adidas Samba: Worth ever...
10397,sha7t764lt9t,Facebook,4999.0,1376,878,Just unboxed my new Xbox Elite Controller from...
865,yhxvwx8u4gqk,Twitter,4999.0,1643,714,Not sure why with my new Nest Thermostat from ...
5511,qgzkmn6gh31d,YouTube,4999.0,489,712,Comparing Toyota Tacoma to the competition. Di...
7859,dfjuykszr588,Unknown,4998.0,386,937,Unknown
12266,krs5f8l99s3m,Instagram,4998.0,842,987,Has anyone else experienced delivery delays wi...
6452,jbm8b5q8ek1t,Facebook,4997.0,658,712,Just tried the Coca-Cola Vanilla from Coca-Col...

TOP 10 POSTS BY SHARES

,post_id,platform,likes,shares,comments,text_content
6332,euvr0r10wrj6,Facebook,453.0,2000,408,Just unboxed my new Zoom Pegasus from Nike. Wo...
3166,wawuzgytmd76,Reddit,1869.0,2000,795,Just saw an ad for Nike Air Max during the Hol...
9073,fbkrqxjkbfyl,Instagram,2502.0,2000,535,Not sure why with my new Nest Hub from Google!...
10322,qq86lkjrfzlt,YouTube,897.0,1999,850,Just unboxed my new RAV4 from Toyota. Not wort...
9526,s9ennlodwowm,Facebook,2398.0,1999,220,My one month review of Nike React: Wouldn't re...
5911,oiszojqm6qnn,Instagram,390.0,1999,858,Just unboxed my new Vision Pro from Apple. Wou...
7593,2xcg9ld7du67,Twitter,1425.0,1999,440,Just tried the Kindle from Amazon. Does the jo...
6955,yu24m2btljaj,Facebook,2305.0,1999,162,My two days review of Google Nest Hub: Worth e...
12256,vzdc847hov6u,Instagram,1470.0,1998,861,Pepsi PowerRelease is underwhelming! Can't wai...
7583,ne28w983w8p6,Unknown,2502.0,1998,708,Just saw an ad for Apple iPad Air during the S...

TOP 10 POSTS BY COMMENTS

,post_id,platform,likes,shares,comments,text_content
6910,6mdlugkjtgmh,Instagram,2502.0,1736,1000,Unknown
6930,xoistx7gh5xw,Reddit,1486.0,907,1000,Bummed out with my new Galaxy Z Fold from Sams...
7076,6viq2n7poav6,Unknown,737.0,820,1000,Adidas SustainableFuture is disappointing! Can...
5811,r7whbtbia4vr,YouTube,1367.0,1324,1000,Just tried the Apple Watch from Apple. Best pu...
9492,udarxdsrykr5,Instagram,1362.0,471,1000,Just saw an ad for Nike Dri-FIT during the Cyb...
6340,cd65aqs67yse,Reddit,905.0,155,1000,"Any advice about Coca-Cola's Diet Coke? #Tech,..."
1588,x9vyodex8s09,Facebook,3240.0,1543,1000,My two days review of Apple AirPods Pro: Retur...
10354,pr7v9tbxo3td,Unknown,3197.0,1077,1000,Just tried the Surface Pro from Microsoft. Ret...
7187,z2lp522fyre5,Unknown,2938.0,618,1000,Just tried the Kindle from Amazon. Not bad. #E...
6080,wsse413uz3hi,Instagram,4526.0,1711,1000,Just unboxed my new Pepsi Max from Pepsi. High...

In [44]:
print("Posts with exactly 5,000 likes:")
print((posts_clean["likes"] == 5000).sum())

print("\nPosts with exactly 2,000 shares:")
print((posts_clean["shares"] == 2000).sum())

print("\nPosts with exactly 1,000 comments:")
print((posts_clean["comments"] == 1000).sum())

print("\nPercentage of posts at each maximum:")

print(
    "Likes:",
    round((posts_clean["likes"] == 5000).mean() * 100, 2),
    "%"
)

print(
    "Shares:",
    round((posts_clean["shares"] == 2000).mean() * 100, 2),
    "%"
)

print(
    "Comments:",
    round((posts_clean["comments"] == 1000).mean() * 100, 2),
    "%"
)

Posts with exactly 5,000 likes:
4

Posts with exactly 2,000 shares:
3

Posts with exactly 1,000 comments:
10

Percentage of posts at each maximum:
Likes: 0.03 %
Shares: 0.02 %
Comments: 0.08 %

In [45]:
# Find the 90th percentile threshold for likes

likes_90th = posts_clean["likes"].quantile(0.90)

print("90th percentile of likes:", likes_90th)

# Count highly liked posts by platform
high_like_posts = posts_clean[
    posts_clean["likes"] >= likes_90th
]

print("\nNumber of highly liked posts:")
print(high_like_posts["platform"].value_counts())

print("\nPercentage of posts that are highly liked:")
print(
    (high_like_posts["platform"].value_counts(normalize=True) * 100).round(2)
)

90th percentile of likes: 4373.0

Number of highly liked posts:
platform
Facebook     228
Reddit       204
Twitter      200
Instagram    195
YouTube      190
Unknown      186
Name: count, dtype: int64

Percentage of posts that are highly liked:
platform
Facebook     18.95
Reddit       16.96
Twitter      16.63
Instagram    16.21
YouTube      15.79
Unknown      15.46
Name: proportion, dtype: float64

In [46]:
# Percentage of each platform's posts that are in the overall top 10% of likes

platform_high_like_rate = (
    posts_clean.assign(
        high_like=posts_clean["likes"] >= likes_90th
    )
    .groupby("platform")["high_like"]
    .mean()
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
)

print("Percentage of each platform's posts in the top 10% of likes:")
print(platform_high_like_rate)

Percentage of each platform's posts in the top 10% of likes:
platform
Facebook     10.99
Unknown      10.43
Reddit       10.04
Instagram     9.80
Twitter       9.76
YouTube       9.17
Name: high_like, dtype: float64

In [47]:
# Number of posts per user

posts_per_user = posts_clean["user_id"].value_counts()

print("Posts per user:")
print(posts_per_user.describe())

print("\nMost active users:")
print(posts_per_user.head(10))

print("\nUsers with only 1 post:")
print((posts_per_user == 1).sum())

print("\nUsers with 10 or more posts:")
print((posts_per_user >= 10).sum())

Posts per user:
count    1500.000000
mean        8.000000
std         2.851214
min         1.000000
25%         6.000000
50%         8.000000
75%        10.000000
max        22.000000
Name: count, dtype: float64

Most active users:
user_id
user_zqv2vrf5    22
user_nfo3ih5u    19
user_8wk0j5ae    18
user_n0ok02rt    18
user_q3vs0uj7    18
user_0irp4abu    17
user_xetn4exw    16
user_ujllj1n7    16
user_i1e1kek5    16
user_uerv85na    16
Name: count, dtype: int64

Users with only 1 post:
2

Users with 10 or more posts:
424

In [48]:
# Merge user information with posts

posts_with_users = posts_clean.merge(
    users_clean,
    on="user_id",
    how="left"
)

print("Merged dataset shape:", posts_with_users.shape)

print("\nMissing follower counts after merge:")
print(posts_with_users["follower_count"].isna().sum())

print("\nCorrelation with follower count:")
print(
    posts_with_users[
        ["follower_count", "likes", "shares", "comments"]
    ].corr()["follower_count"].round(3)
)

Merged dataset shape: (12000, 13)

Missing follower counts after merge:
0

Correlation with follower count:
follower_count    1.000
likes             0.008
shares           -0.014
comments         -0.000
Name: follower_count, dtype: float64

In [49]:
# Average engagement by language

language_engagement = (
    posts_with_users
    .groupby("language")[["likes", "shares", "comments"]]
    .mean()
    .round(2)
    .sort_values("likes", ascending=False)
)

print("Average engagement by language:")
print(language_engagement)

Average engagement by language:
            likes   shares  comments
language
en        2556.70   997.11    504.18
ar        2536.54  1032.73    495.48
ja        2508.02   995.97    510.10
zh        2505.29  1022.98    500.12
fr        2499.38   980.25    519.76
pt        2493.83  1036.90    509.70
ru        2488.13   991.12    512.72
de        2477.94  1003.82    498.80
es        2467.65  1032.32    488.74
hi        2420.40   981.56    503.90

In [50]:
# Number and percentage of posts by language

language_distribution = (
    posts_with_users["language"]
    .value_counts()
    .to_frame("post_count")
)

language_distribution["percentage"] = (
    language_distribution["post_count"]
    / len(posts_with_users)
    * 100
).round(2)

print(language_distribution)

          post_count  percentage
language
zh              1369       11.41
ja              1298       10.82
hi              1291       10.76
en              1220       10.17
fr              1156        9.63
de              1149        9.57
es              1143        9.52
pt              1132        9.43
ar              1123        9.36
ru              1119        9.32

In [51]:
# Check account_created values

print("Data type:")
print(users_clean["account_created"].dtype)

print("\nFirst 10 values:")
print(users_clean["account_created"].head(10))

print("\nUnique date formats / examples:")
print(users_clean["account_created"].sample(10, random_state=42).tolist())

print("\nMissing values:")
print(users_clean["account_created"].isna().sum())

Data type:
object

First 10 values:
0    2023-10-23
1    2023-05-06
2    2023-01-03
3    2023-10-11
4    2023-05-23
5    2023-03-17
6    2023-12-01
7    2023-03-30
8    2023-12-03
9    2023-12-21
Name: account_created, dtype: object

Unique date formats / examples:
['2023-03-28', '2023-09-10', '2023-12-18', '2023-12-19', '2023-08-14', '2023-11-19', '2023-12-17', '2023-05-30', '2023-09-25', '2023-02-26']

Missing values:
0

In [52]:
# Standardize account_created as a datetime column

users_clean["account_created"] = pd.to_datetime(
    users_clean["account_created"],
    format="%Y-%m-%d",
    errors="coerce"
)

print("Data type after conversion:")
print(users_clean["account_created"].dtype)

print("\nMissing values after conversion:")
print(users_clean["account_created"].isna().sum())

print("\nDate range:")
print(users_clean["account_created"].min(), "to", users_clean["account_created"].max())

Data type after conversion:
datetime64[ns]

Missing values after conversion:
0

Date range:
2023-01-01 00:00:00 to 2023-12-31 00:00:00

In [53]:
# Check for suspicious text-encoding artifacts

encoding_pattern = r"Ã|Â|â€™|â€œ|â€|ð"

suspicious_text = posts_clean[
    posts_clean["text_content"].notna()
    & posts_clean["text_content"].astype(str).str.contains(
        encoding_pattern,
        regex=True,
        na=False
    )
]

print("Number of posts with suspicious encoding artifacts:")
print(len(suspicious_text))

print("\nExamples:")
print(suspicious_text["text_content"].head(10).tolist())

Number of posts with suspicious encoding artifacts:
287

Examples:
['Just unboxed my new Halo Band from Amazon. Exceeded my expectations. Confused about #Food, #TravelÃ©', 'Comparing Adidas Samba to the competition. Exceeded my expectations. #Trending, #Promo Would love to get your feedback!Ã©', 'Just saw an ad for Apple Vision Pro during the SpringBlast2025. Highly recommend. #Sustainable, #Tech, #FitnessÃ©', 'Just tried the React from Nike. Best purchase ever. #Beauty, #Sale Curious about your experience too.Ã©', 'Comparing Amazon Fire Tablet to the competition. Highly recommend. #Promo Let me know what you think!Ã©', 'Comparing Google Chromebook to the competition. Not worth the money. #Reviews Curious about your experience too.Ã©', "Adidas WinterWonders is frustrating! Can't wait to see what's coming next. #Fashion, #Tech Really interested in hearing your thoughts!Ã©", "Anyone have tips about Pepsi's Pepsi Zero Sugar? @BrandCEO, @CelebrityName #SpecialOffer, #NewRelease Would love to get your feedback!Ã©", "Just unboxed my new Galaxy Tab from Samsung. Absolutely loving it. Can't contain my excitement #Limited, #Fitness, #FashionÃ©", "Coca-Cola HolidaySpecial is amazing! Can't wait to see what's coming next. #Lifestyle Curious about your experience too.Ã©"]

In [54]:
# Test UTF-8 encoding repair on suspicious text

def fix_encoding(text):
    if pd.isna(text):
        return text

    text = str(text)

    try:
        return text.encode("latin1").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text


# Apply only to suspicious rows for testing
encoding_test = suspicious_text["text_content"].apply(fix_encoding)

print("Before → After:\n")

for before, after in zip(
    suspicious_text["text_content"].head(10),
    encoding_test.head(10)
):
    print("BEFORE:", before)
    print("AFTER :", after)
    print()

Before → After:

BEFORE: Just unboxed my new Halo Band from Amazon. Exceeded my expectations. Confused about #Food, #TravelÃ©
AFTER : Just unboxed my new Halo Band from Amazon. Exceeded my expectations. Confused about #Food, #Travelé

BEFORE: Comparing Adidas Samba to the competition. Exceeded my expectations. #Trending, #Promo Would love to get your feedback!Ã©
AFTER : Comparing Adidas Samba to the competition. Exceeded my expectations. #Trending, #Promo Would love to get your feedback!é

BEFORE: Just saw an ad for Apple Vision Pro during the SpringBlast2025. Highly recommend. #Sustainable, #Tech, #FitnessÃ©
AFTER : Just saw an ad for Apple Vision Pro during the SpringBlast2025. Highly recommend. #Sustainable, #Tech, #Fitnessé

BEFORE: Just tried the React from Nike. Best purchase ever. #Beauty, #Sale Curious about your experience too.Ã©
AFTER : Just tried the React from Nike. Best purchase ever. #Beauty, #Sale Curious about your experience too.é

BEFORE: Comparing Amazon Fire Tablet to the competition. Highly recommend. #Promo Let me know what you think!Ã©
AFTER : Comparing Amazon Fire Tablet to the competition. Highly recommend. #Promo Let me know what you think!é

BEFORE: Comparing Google Chromebook to the competition. Not worth the money. #Reviews Curious about your experience too.Ã©
AFTER : Comparing Google Chromebook to the competition. Not worth the money. #Reviews Curious about your experience too.é

BEFORE: Adidas WinterWonders is frustrating! Can't wait to see what's coming next. #Fashion, #Tech Really interested in hearing your thoughts!Ã©
AFTER : Adidas WinterWonders is frustrating! Can't wait to see what's coming next. #Fashion, #Tech Really interested in hearing your thoughts!é

BEFORE: Anyone have tips about Pepsi's Pepsi Zero Sugar? @BrandCEO, @CelebrityName #SpecialOffer, #NewRelease Would love to get your feedback!Ã©
AFTER : Anyone have tips about Pepsi's Pepsi Zero Sugar? @BrandCEO, @CelebrityName #SpecialOffer, #NewRelease Would love to get your feedback!é

BEFORE: Just unboxed my new Galaxy Tab from Samsung. Absolutely loving it. Can't contain my excitement #Limited, #Fitness, #FashionÃ©
AFTER : Just unboxed my new Galaxy Tab from Samsung. Absolutely loving it. Can't contain my excitement #Limited, #Fitness, #Fashioné

BEFORE: Coca-Cola HolidaySpecial is amazing! Can't wait to see what's coming next. #Lifestyle Curious about your experience too.Ã©
AFTER : Coca-Cola HolidaySpecial is amazing! Can't wait to see what's coming next. #Lifestyle Curious about your experience too.é

In [55]:
# Repair suspicious text-encoding artifacts

encoding_mask = (
    posts_clean["text_content"].notna()
    & posts_clean["text_content"].astype(str).str.contains(
        encoding_pattern,
        regex=True,
        na=False
    )
)

# Count affected rows before repair
affected_before = encoding_mask.sum()

# Apply the repair
posts_clean.loc[encoding_mask, "text_content"] = (
    posts_clean.loc[encoding_mask, "text_content"].apply(fix_encoding)
)

print("Posts repaired:", affected_before)

Posts repaired: 287

In [56]:
# Verify that suspicious encoding artifacts are gone

remaining_encoding = posts_clean[
    posts_clean["text_content"].notna()
    & posts_clean["text_content"].astype(str).str.contains(
        encoding_pattern,
        regex=True,
        na=False
    )
]

print("Remaining suspicious encoding artifacts:", len(remaining_encoding))

if len(remaining_encoding) > 0:
    print("\nRemaining examples:")
    print(remaining_encoding["text_content"].head(10).tolist())
else:
    print("Text encoding check passed: no suspicious artifacts remain.")

Remaining suspicious encoding artifacts: 0
Text encoding check passed: no suspicious artifacts remain.

In [57]:
# Check platform values for consistency

print("Unique platform values:")
print(posts_clean["platform"].unique())

print("\nNumber of unique platform values:")
print(posts_clean["platform"].nunique())

Unique platform values:
['Reddit' 'Unknown' 'Facebook' 'Twitter' 'Instagram' 'YouTube']

Number of unique platform values:
6

In [58]:
# FINAL DATA-QUALITY AUDIT FOR POSTS

print("========== FINAL POSTS AUDIT ==========\n")

print("Shape:")
print(posts_clean.shape)

print("\nDuplicate rows:")
print(posts_clean.duplicated().sum())

print("\nDuplicate post IDs:")
print(posts_clean["post_id"].duplicated().sum())

print("\nMissing values:")
print(posts_clean.isna().sum())

print("\nNegative likes:")
print((posts_clean["likes"] < 0).sum())

print("\nNegative shares:")
print((posts_clean["shares"] < 0).sum())

print("\nNegative comments:")
print((posts_clean["comments"] < 0).sum())

print("\nInvalid timestamps:")
print(posts_clean["timestamp"].isna().sum())

print("\nUnique users in posts:")
print(posts_clean["user_id"].nunique())

print("\nPlatform values:")
print(posts_clean["platform"].value_counts())

========== FINAL POSTS AUDIT ==========

Shape:
(12000, 9)

Duplicate rows:
0

Duplicate post IDs:
0

Missing values:
post_id         0
user_id         0
platform        0
text_content    0
timestamp       0
likes           0
shares          0
comments        0
month           0
dtype: int64

Negative likes:
0

Negative shares:
0

Negative comments:
0

Invalid timestamps:
0

Unique users in posts:
1500

Platform values:
platform
Facebook     2074
YouTube      2073
Twitter      2049
Reddit       2031
Instagram    1989
Unknown      1784
Name: count, dtype: int64

In [59]:
# Remove the temporary EDA helper column

posts_clean = posts_clean.drop(columns=["month"])

print("Final cleaned Posts shape:")
print(posts_clean.shape)

print("\nFinal columns:")
print(posts_clean.columns.tolist())

Final cleaned Posts shape:
(12000, 8)

Final columns:
['post_id', 'user_id', 'platform', 'text_content', 'timestamp', 'likes', 'shares', 'comments']

In [60]:
# Check final data types before export

print("Final data types:")
print(posts_clean.dtypes)

print("\nFirst 5 rows:")
print(posts_clean.head())

Final data types:
post_id                 object
user_id                 object
platform                object
text_content            object
timestamp       datetime64[ns]
likes                  float64
shares                   int64
comments                 int64
dtype: object

First 5 rows:
        post_id        user_id  platform  \
0  to64mgey2v3y  user_vfxs1pry    Reddit
1  7f0wdauzbj89  user_8l7rv5oe    Reddit
2  dvvhg8eel45x  user_nfo3ih5u   Unknown
3  hgb9cxke4t7b  user_27aje6ur  Facebook
4  zwerpw3wk320  user_9px5q0by    Reddit

                                        text_content           timestamp  \
0  Bummed out with my new Air Max from Nike! Abso... 2024-09-25 00:00:00
1  My one month review of Pepsi Crystal Pepsi: Hi... 2024-08-01 16:14:00
2  Just unboxed my new Highlander from Toyota. Ex... 2025-04-13 20:12:18
3  Comparing Pepsi Crystal Pepsi to the competiti... 2024-09-10 00:00:00
4  My one week review of Coca-Cola Diet Coke: Bes... 2024-05-31 00:00:00

    likes  shares  comments
0  4488.0    1456       673
1   789.0    1484        39
2  2502.0    1410       839
3   167.0     584       833
4  4749.0     152       630

In [61]:
# Convert likes from float to integer

posts_clean["likes"] = posts_clean["likes"].astype("int64")

print("Final data types:")
print(posts_clean.dtypes)

print("\nLikes check:")
print(posts_clean["likes"].head(10).tolist())

Final data types:
post_id                 object
user_id                 object
platform                object
text_content            object
timestamp       datetime64[ns]
likes                    int64
shares                   int64
comments                 int64
dtype: object

Likes check:
[4488, 789, 2502, 167, 4749, 3694, 2502, 434, 4798, 2793]

In [62]:
# Export the final cleaned Posts dataset

output_file = "Data_Vortex_Cleaned_Dataset.csv"

posts_clean.to_csv(
    output_file,
    index=False
)

print("Cleaned dataset saved successfully!")
print("File:", output_file)
print("Rows:", len(posts_clean))
print("Columns:", len(posts_clean.columns))

Cleaned dataset saved successfully!
File: Data_Vortex_Cleaned_Dataset.csv
Rows: 12000
Columns: 8

In [63]:
# Reload the exported CSV and verify it

verified_posts = pd.read_csv("Data_Vortex_Cleaned_Dataset.csv")

print("Verified shape:")
print(verified_posts.shape)

print("\nVerified columns:")
print(verified_posts.columns.tolist())

print("\nMissing values:")
print(verified_posts.isna().sum())

print("\nDuplicate rows:")
print(verified_posts.duplicated().sum())

print("\nDuplicate post IDs:")
print(verified_posts["post_id"].duplicated().sum())

print("\nNegative engagement values:")
print("Likes:", (verified_posts["likes"] < 0).sum())
print("Shares:", (verified_posts["shares"] < 0).sum())
print("Comments:", (verified_posts["comments"] < 0).sum())

Verified shape:
(12000, 8)

Verified columns:
['post_id', 'user_id', 'platform', 'text_content', 'timestamp', 'likes', 'shares', 'comments']

Missing values:
post_id         0
user_id         0
platform        0
text_content    0
timestamp       0
likes           0
shares          0
comments        0
dtype: int64

Duplicate rows:
0

Duplicate post IDs:
0

Negative engagement values:
Likes: 0
Shares: 0
Comments: 0